kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-px-01
  namespace: default
spec:
  storageClassName: pxd-portworx-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

